### ISSUE TITLE
Rules to submit questions

### ISSUE THREAD

**Issue by setiadijoe** [jabardigitalservice/QnA#2]
Hello team Jabar Digital Services!

I was wondering about this repo about qna. So what will be provide on this QnA?

Thankyou

**Comment by rindibudiaramdhan** [comment]
halo kang @setiadijoe ! Lama tidak berjumpa!
yup, QnA Jabar Digital Service adalah platform untuk membantu teman-teman <i>Engineer</i> mengajukan pertanyaan, belajar, dan berbagi pengetahuan teknis.

Kalau kang @setiadijoe ada isu, pertanyaan terkait teknis programming dan sekitarnya, bisa dibuatkan issue disini.
