### ISSUE TITLE
JDS test-stack

### ISSUE THREAD

**Issue by depapp** [jabardigitalservice/QnA#3]
halo semuanya, salama kenal..
saya mau bertanya terkait testing tools yang dipake di JDS itu seperti apa ya? seperti ui & api automation test, etc 🙇🏻

**Comment by firmanJS** [comment]
ada mastah @depapp 

disundul babang @rindibudiaramdhan @sandisunandar99 @azophy

**Comment by rizkiamiftah** [comment]
halo @depapp, izin jawab ya di JDS untuk tools yang digunakan 

- UI/E2E : cypress, test project.io
- API : postman runner
- Load Test : Jmeter, K6

nextnya ingin coba riset tools seperti webdriver.io, appium, bdd gherkin 😄

**Comment by sandisunandar99** [comment]
> ada mastah @depapp
> 
> disundul babang @rindibudiaramdhan @sandisunandar99 @azophy

halo babank tampvan,, 😆 
oia yg di jawab di atas kita pake itu ya.. 👍

**Comment by sandisunandar99** [comment]
> ada mastah @depapp
> 
> disundul babang @rindibudiaramdhan @sandisunandar99 @azophy

halo babank tampvan,, 😆 
oia yg di jawab di atas kita pake itu ya.. 👍

**Comment by sandisunandar99** [comment]
> ada mastah @depapp
> 
> disundul babang @rindibudiaramdhan @sandisunandar99 @azophy

halo babank tampvan,, 😆

**Comment by depapp** [comment]
terima kasih mas @rizkiamiftah untuk jawabannya 🙇🏻 
klo testproject.io itu berarti untuk mobile ui automation nya mas?


> nextnya ingin coba riset tools seperti webdriver.io, appium, bdd gherkin 😄

barangkali mau coba liat-liat ini mas https://www.npmjs.com/package/pusakatest - 
api automation dengan bdd-style tanpa harus susah-susah setup env ini dan itu 😅

**Comment by rizkiamiftah** [comment]
sama2 mas @depapp 
iya mas test project.io dipake juga buat web automation hehe

wahh mantaps makasih banyak mas sharingnya 👍
