### ISSUE TITLE
Biasanya kalau development laravel menggunakan IDE apa ya?

### ISSUE THREAD

**Issue by rhmnmbr** [jabardigitalservice/QnA#4]
Saya development laravel pakai vscode tapi koq intelisense nya kayak gak smart ya, padahal sudah install beberapa ekstensi seperti intelephense.
Mungkin temen-temen bisa bantu share terkait ini.

**Comment by sandisunandar99** [comment]
> Saya development laravel pakai vscode tapi koq intelisense nya kayak gak smart ya, padahal sudah install beberapa ekstensi seperti intelephense. Mungkin temen-temen bisa bantu share terkait ini.

kalo si kami sih biasanya pake paket hemat yg ini 

https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-extension-pack

**Comment by rhmnmbr** [comment]
![image](https://user-images.githubusercontent.com/34632080/187464861-f0ffa4a2-5f78-448f-ab96-7f45b879fe0b.png)

sudah menggunakan extension `Laravel Snippets` dari Winnie Lien dan `Laravel Extra Intellisense` dari amir, tapi `::where` tetap gak muncul di opsi nya ya, tapi sebetulnya codingan jalan2 aja sih.

**Comment by rindibudiaramdhan** [comment]
Halo, kang @rhmnmbr83 kalau saya pakai vscode. extentionnya saya installnya macem2 sih. ini juga rekomendasi dari banyak sumber, tapi lupa linknya. ini extension yang saya pakai di vscode

<img width="573" alt="image" src="https://user-images.githubusercontent.com/19951241/187589780-80d386ea-3a13-4ed0-95c9-1eb3f9845fc2.png">
<img width="575" alt="image" src="https://user-images.githubusercontent.com/19951241/187589798-53a1c825-1045-4686-8832-a51366ee5692.png">

## PHP Extension
<img width="575" alt="image" src="https://user-images.githubusercontent.com/19951241/187589858-9ca57a0b-606d-4c68-87f3-1f20bdc10b0b.png">
<img width="531" alt="image" src="https://user-images.githubusercontent.com/19951241/187589913-913d6903-f65e-4182-985b-f4b08e904597.png">
<img width="535" alt="image" src="https://user-images.githubusercontent.com/19951241/187589946-6427fc65-3c03-4f1f-95fe-4cf561b0e655.png">
<img width="528" alt="image" src="https://user-images.githubusercontent.com/19951241/187590085-7aade472-c734-4134-bdf0-ac3877ff061b.png">
<img width="527" alt="image" src="https://user-images.githubusercontent.com/19951241/187590116-fd1c7b9c-bb4c-4937-9b20-6aba37b8b48b.png">
<img width="529" alt="image" src="https://user-images.githubusercontent.com/19951241/187590150-37041951-54cb-4ff7-96f2-b7bae500714d.png">

**Comment by azophy** [comment]
Denger-denger PHPStorm memang lebih powerfull kalau soal fitur2 spesifik PHP macam gini. Belum pernah pake sih, tapi memang kalau soal tools gini baiknya coba-coba dan eksperimen sendiri.

**Comment by rindibudiaramdhan** [comment]
> Denger-denger PHPStorm memang lebih powerfull kalau soal fitur2 spesifik PHP macam gini. Belum pernah pake sih, tapi memang kalau soal tools gini baiknya coba-coba dan eksperimen sendiri.

premium soalnya kang @azophy . mas @yohang88 yang pernah pakai PHPStorm ini. minta pros cons nya mase~ 😁

**Comment by rhmnmbr** [comment]
https://laracasts.com/series/how-to-be-awesome-in-phpstorm/episodes/15 ini sepertinya referensi yang bagus, nanti saya coba
atau mungkin lebih bagus lagi phpstrom + https://laravel-idea.com/ ini bagus, cuma berbayar 😅
