### ISSUE TITLE
Offset Pagination vs Cursor Pagination

### ISSUE THREAD

**Issue by samudra-ajri** [jabardigitalservice/QnA#5]
What type of pagination that JDS uses mostly for their products?
Would you like to share how the JDS's way to decide these paginations types?

Regards,
😁

**Comment by rindibudiaramdhan** [comment]
sebelum kesana, intro dulu yang ini kang @samudra-ajri  hehe
[KENAPA PAGINATION ITU LAMBAT - YouTubehttps://www.youtube.com › watch](https://www.youtube.com/watch?v=53MNk1hmRTw)

btw ini pernah ada pertanyaan yang sama terkait pemilihan pagination.
https://stackoverflow.com/questions/55744926/offset-pagination-vs-cursor-pagination

dan ada comment juga terkait ini,
> With cursor pagination, when the user clicks next or previous to see a new page, it will take only 0.18 seconds to load. With offset pagination, the same action will take 13 seconds! That means each page will take 13 seconds to load.

[Is offset pagination dead? Why cursor pagination is taking overhttps://uxdesign.cc › why-facebook-says-cursor-paginatio...](https://uxdesign.cc/why-facebook-says-cursor-pagination-is-the-greatest-d6b98d86b6c0#:~:text=With%20cursor%20pagination%2C%20when%20the,take%2013%20seconds%20to%20load.)

**Comment by samudra-ajri** [comment]
Mantap, Kang..
Klw di jds menentukan tipe paginasinya seperti apa ya, Kang? Karena beberapa repo publik jds yg saya buka kebanyakan mengguanakn offset paginasi nih, Kang.

Regards,
😁

**Comment by rindibudiaramdhan** [comment]
> Mantap, Kang.. Klw di jds menentukan tipe paginasinya seperti apa ya, Kang? Karena beberapa repo publik jds yg saya buka kebanyakan mengguanakn offset paginasi nih, Kang.
> 
> Regards, 😁

betul kang @samudra-ajri . kebanyakan menggunakan offset paginasi.
Saya, khususnya mencari cara paling cepat dan sudah banyak digunakan dari awal terkait paginasi ini, yaitu menggunakan offset.

Selanjutnya lebih ke optimasi/improvement API yang akan kita gunakan. Apakah dengan offset paginasi ini sudah cukup, atau perlu optimasi tambahan terkait ini. Bisa beragam faktor, dengan penambahan tools2 lainnya (misal REDIS dsb) yang membantu mengurangi secara signifikan (yang sangat berefek ke user/client) yaitu response time.

CMIIW
