### ISSUE TITLE
Production Seeding Best Practice

### ISSUE THREAD

**Issue by fajarhikmal214** [jabardigitalservice/QnA#6]
## Background :
- Di sebuah project memiliki sebuah data yang harus di _generate_ untuk beberapa keperluan
- Untuk sekarang di _handle_ dengan menggunakan _migration_ dan _seeder_ via _Object Relation Mapping_ (ORM)

## Problem :
- Apakah bermasalah jika implementasi seeder di local, staging dan production sama menggunakan ORM ?
- Apa solusi _best practice_ untuk _seeding_ data di production ?

## What I Found :
- Di sebuah forum ada yang berpendapat bahwa "_I wouldn't use a seeder for production data_"
- Bagaimana dengan saya membuat migrasi untuk tabel. Kemudian, saya membuat schema.sql yang menyertakan perintah _create table_ dan menyisipkan setiap baris. Saya menjalankan Migrasi, yang membuat tabel. Saya kemudian secara manual mengimpor schema.sql ke _database_.

## Question :
- Apakah tergantung dengan kerasahasiaan datanya ? Maksudnya ketika tidak memungkinkan untuk dibagikan ke publik menggunakan schema.sql dan ketika memungkinkan untuk dibagikan ke publik cukup menggunakan seeder.

Apa pendapatmu ?

Refs. https://laracasts.com/discuss/channels/general-discussion/production-seeding-best-practice

**Comment by azophy** [comment]
Ini topik yang saya juga masih cari-cari referensinya dari kemarin. Sejauh ini belum ketemu sumber yang komprehensif, tapi ada beberapa kesimpulan yang sudah bisa saya ambil :

1. Sebaiknya bedakan seeding data yang sifatnya dinamis/random (biasanya berisi kode-kode Faker/Mocker, tujuannya lebih untuk automated test) vs yang sifatnya statis (untuk keperluan staging/production). Prakteknya misalnya dengan membuat beberapa file seeder untuk jenis yang berbeda.
2. Untuk yang sifatnya statis, sesuai namanya sebaiknya semua isinya dibuat statis juga (termasuk kolom id, created_at, dan sejenisnya). Tujuannya agar nanti kalau ada data seeder nya berubah bisa dilakukan operasi update/delete. Contohnya dibahas di [thread StackOverflow ini](https://stackoverflow.com/a/61193649/2496217) .
3. Kalau file seeding ini ternyata dibutuhkan di semua environment (termasuk untuk automated testing), salah satu teknik yang bisa dicoba adalah dengan memasukkan kode seeding yang sudah ada ke file migration. Di Laravel memungkinkan untuk memanggil seeder dari migration seperti yang [dicontohnya di sini](https://stackoverflow.com/a/54227917/2496217) . Tentu ada plus-minusnya kalau seperti ini karena berarti kalau ada perubahan data seeder, idealnya perubahan tersebut juga terekam di migration.

**Comment by rindibudiaramdhan** [comment]
setuju dengan poin-poin yang disampaikan @azophy 
kalau saya memegang "mazhab" sebisa mungkin tidak melakukan seeding di production.
seeding saya anggap penggunaannya dilakukan untuk memudahkan developer dalam pengujian (Unit Test/Feature Test) dalam environment local.

big concernnya karena:
- _security reason. Credential expose caution._
- _Some seeding operations may cause you to alter or lose data._ https://laravel.com/docs/9.x/seeding#forcing-seeding-production
